package br.com.restfulcrud.model;
// Generated 12/03/2016 12:00:39 by Hibernate Tools 3.4.0.CR1

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Produtos generated by hbm2java
 */
@XmlRootElement
public class Produtos implements java.io.Serializable {

	private Integer id;
	private String nome;
	private String tipo;
	private float preco;
	private String descricao;

	public Produtos() {
	}

	public Produtos(String nome, String tipo, float preco, String descricao) {
		this.nome = nome;
		this.tipo = tipo;
		this.preco = preco;
		this.descricao = descricao;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public float getPreco() {
		return this.preco;
	}

	public void setPreco(float preco) {
		this.preco = preco;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

}
